node --version
npm install eslint
npm install prettier
npm install htmlhint
npx prettier --check
npx prettier --run
npx prettier --w
npx prettier --check"{html,css,js}"
npx prettier -w.
npx htmlhint "**/*.html"
